### ISSUE TITLE
[English support]: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by flyingFalcon22** [WoW-CMS/support#1]
# Wow-CMS English support

### What operating system are you using?
- [x] Linux

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] VPS

### Which emulator are you using and which version?
- [x] TrinityCore

### Describe the bug
- I tried to install the CMS. after the first page (mysql info) I get this error. All the request are installed.

### How can I reproduce the problem?

1.Unzipt BlizzCMS-1.0.7.4
2.Insert mysql infos
3.Go to next page.
4.You get the error

### Screenshots
![image](https://user-images.githubusercontent.com/81469821/117553215-744ce200-b050-11eb-9258-078f4df41901.png)

**Comment by pangolp** [comment]
In addition to the PHP version. The CMS requires a number of extensions. Among which, there is one that is named just like the `curl` error. Which version of PHP are you using, Apache or Ngnix?

**Comment by flyingFalcon22** [comment]
@pangolp  Apache. the curl is installed and enabled in php.ini

**Comment by pangolp** [comment]
> @pangolp Apache. the curl is installed and enabled in php.ini

What command did you use to install the dependency?

**Comment by flyingFalcon22** [comment]
![image](https://user-images.githubusercontent.com/81469821/117553598-d3abf180-b052-11eb-8ee5-c26036a15d39.png)

**Comment by pangolp** [comment]
In linux it is not necessary to enable the extension in the php.ini, at least, the times I did the installation it was not necessary and in fact, sometimes it takes it as a double enable. Try commenting out the curl line, and if it doesn't work, we will continue analyzing the problem.

**Comment by flyingFalcon22** [comment]
It works now. After commenting  all the lines curl, soap, etc and restart the machine works all.  Thanks for the help.

**Comment by pangolp** [comment]
No problem. Good luck.
