### ISSUE TITLE
[Soporte en Español] Problema al crear noticias

### ISSUE THREAD

**Issue by d3athbl0w** [WoW-CMS/support#13]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [X] Windows

##### ¿Qué versión de PHP utiliza?
- [X] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [X] Github

##### ¿Dónde está tratando de instalar el CMS?
- [X] Web Hosting

##### ¿Qué emulador estás usando y qué versión?
- [X] MaNGOS

##### Describa el bug
- Tengo error al crear una noticia.

##### ¿Cómo puedo reproducir el problema?

1. Ir al admin panel
2. Crear una noticia
3. Saldrá un error 404

##### Capturas de pantalla
![Captura](https://user-images.githubusercontent.com/14060040/141668062-b732b3f7-7f0b-408a-848d-4699212a208b.PNG)

**Comment by d3athbl0w** [comment]
![el error](https://user-images.githubusercontent.com/14060040/141668272-819c497d-f395-4ba9-9c8d-4258bce4c371.PNG)

El error aparece cuando trato de centrar las noticias.

**Comment by pangolp** [comment]
¿404 o 403? Porque en la imagen se ve un error 403, que es de permisos. El 404 es de que no se puede encontrar. Son 2 errores diferentes. De todos modos, tendré que testearlo. ¿Estas usando la ultima versión del repositorio?

**Comment by pangolp** [comment]
Si el problema persiste, le pido que mas adelante, cree otro informe, pero voy a cerrar el terma, porque al parecer, no volvió a ocurrir o se ve que pudo solucionar su problema.
