### ISSUE TITLE
[Soporte en Español] error durante la instalación

### ISSUE THREAD

**Issue by raxxorx** [WoW-CMS/support#15]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] AzerothCore: Rev.60d90aee3da4 2021-11-24

##### Describa el bug
- Muy buenas, a la hora de tratar de proceder con la migración de cms, me tira un mensaje de error el cual es el siguiente:

```
Not Found
The requested URL was not found on this server.

Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/7.3.31 Server at localhost Port 80
```

**Comment by pangolp** [comment]
¿Qué estas usando xxamp como servidor web o wamp server?

**Comment by raxxorx** [comment]
Xxamp como servidor web.

**Comment by pangolp** [comment]
Revisa el tema de los 2 modulos de Apache2.
- Rewrite
- Expires
- Headers

Y el tema de las extensiones de php, que se describen en el fichero README.md
https://github.com/WoW-CMS/BlizzCMS/blob/master/README.md

**Comment by pangolp** [comment]
¿Le encontró respuesta al problema que tenia? ¿Pudo instalar las dependencias que me mencione?
De ser así, le pido por favor que nos avise y que cierre el tema. Gracias.
