### ISSUE TITLE
[English]: Guardar Cambios Uncontrolled

### ISSUE THREAD

**Issue by wolone** [WoW-CMS/support#16]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

VPS

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

application/modules/user/views/settings.php

`<button class="uk-button uk-button-default uk-width-1-1"><i class="fas fa-sync"></i> Guardar Cambios</button>`

Guardar Cambios Uncontrolled
`<button class="uk-button uk-button-default uk-width-1-1"><i class="fas fa-sync"></i> <?= $this->lang->line('button_save_changes'); ?></button>`

**Comment by pangolp** [comment]
Hi, thanks for the report. I need a little more context to understand the error you are reporting. For example, it would be very helpful, if you could edit your issue and clarify what the steps would be, in order to get the error. Thank you.

**How can I reproduce the problem?**

**Comment by pangolp** [comment]
This issue, I believe, corresponds to the PR that was recently merged, I await confirmation, thank you.
