### ISSUE TITLE
[English]: Items in the store

### ISSUE THREAD

**Issue by JadaDev** [WoW-CMS/support#18]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

VPS

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

If you visit the store and buy any item and than select a character
than buy another item which is more expensive than what you have ( DP )  and also select character
than you go to View cart and make the expensive item negative value -1 for exp and than go buy another random item cheap one.
than you can be able to buy items and no points will be removed from your account and you can buy any items you want.

the fix should be removing the way to put negative values.

**Comment by pangolp** [comment]
Hi, thanks for the report. I need a little more information if possible. Contact me via discord if you wish, to understand the problem a little more. Stevej#5879

**Comment by pangolp** [comment]
My partner confirms that his problem has been corrected. https://github.com/WoW-CMS/BlizzCMS/commit/4a63db3d8616deb2c030be77a52d684d9afc19b1. Sorry for the delay again and thank you for your report.
