### ISSUE TITLE
[English]: CMaNGOS Soap problem 

### ISSUE THREAD

**Issue by alieencz** [WoW-CMS/support#19]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

MaNGOS

### Describe the bug

After installation of BlizzCMS i managed to run  /admin/checksoap to check SOAP connection . But instead of it i get this , but RealmStatus and Characters List is working.
![Snímek obrazovky 2022-03-04 170302](https://user-images.githubusercontent.com/2219648/156797492-9d4895a4-d343-4753-a0b3-9807bd185453.png)

 

### How can I reproduce the problem?

- CMaNGOS TBC Newest Release
- Fresh BlizzCMS 1.0.7.6
- entering /admin/checksoap

**Comment by pangolp** [comment]
Do you get that message when you log into `/en/admin/checksoap`?

**Comment by alieencz** [comment]
im getting message i posted above ..

**Comment by alieencz** [comment]
Yes i get that message entering /en/admin/checksoap yes

**Comment by pangolp** [comment]
Do you have soap enabled on the web server?
Port 7878? or is it all local?
I mean, if the web server and the emulator are on the same machine, I don't think you will have problems with the ports.

![soap](https://user-images.githubusercontent.com/2810187/156799145-d3863f98-1255-4dc3-b8d0-ab5ffe5d2b15.png)

**Comment by alieencz** [comment]
Thank you very much !! i did not have soap extension in xampp enabled.

**Comment by pangolp** [comment]
You are welcome, good luck.
