### ISSUE TITLE
[English]: Server Status -  Always "Offline"

### ISSUE THREAD

**Issue by angrytoilet** [WoW-CMS/support#22]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

The server status for the site is always "offline"
SOAP enabled on the worldserver.conf using default settings (ip:port)
soap reports working in all other aspects of the site (checksoap, pulls data properly, etc etc).  The only "issue" is that the server is never showing "online".  When clicking on the server, you can see people are online, and, who they are.

**Comment by helldragonpz** [comment]
I have the same issue as well

**Comment by angrytoilet** [comment]
We worked with someone yesterday on this matter and we are unable to resolve.
Its seems like the check is simply checking to see if the port itself is open, then, saying "online" if it is, or "offline" if it is not.  Using Netstat -a I can see that the default port is being listened to, and, all the other SOAP related data is being passed.  Sadly, via network traffic, I don't see the site even checking to see if the port is open or not.

Issue at this time is still unresolved.

**Comment by pangolp** [comment]
Thanks to the different conversations we had, and the tests they performed, which helped me to understand the cause of the problem, the problem was solved in the following PR: https://github.com/WoW-CMS/BlizzCMS/pull/57. So I close the topic, because it has been solved. Thank you.
