### ISSUE TITLE
[English]: Races outside of 3.3.5 error/no icon/no faction

### ISSUE THREAD

**Issue by angrytoilet** [WoW-CMS/support#24]
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

AzerothCore

### Describe the bug

Using v1.0.7.6 I have noticed that any race outside of the default "classic" 10 races do not show up properly in the online, or, players list.  The issue is that the races are not being noticed by the systems (Vulpera for example).  Our Zandalari Trolls are also listed and displayed as "Troll".  The faction is also broken for some of the races.
for example:  Vulpera has the "broken image" icon for race as well as faction.

**Comment by pangolp** [comment]
Isn't this report similar to this one: https://github.com/WoW-CMS/support/issues/21?

**Comment by angrytoilet** [comment]
yes, i am not sure why 2 were created for the same issue.  Closing one as a duplicate is fine.
