### ISSUE TITLE
[English support]: TOP Item - BlizzCMS 1.0.7.5

### ISSUE THREAD

**Issue by noxcis12** [WoW-CMS/support#4]
# Wow-CMS English support

### What operating system are you using?
- [x] Linux

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] VPS

### Which emulator are you using and which version?
- [x] AzerothCore

### Describe the bug
- When I add a shop item in top item I have a Php error

### How can I reproduce the problem?

1.Create store item
2. Add in top item

### Screenshots

![1](https://user-images.githubusercontent.com/85730526/121674807-d0bd7a00-cab2-11eb-968a-784a99f584bc.png)
![2](https://user-images.githubusercontent.com/85730526/121674815-d31fd400-cab2-11eb-8d3b-05931cb541ac.png)
![3](https://user-images.githubusercontent.com/85730526/121674822-d4510100-cab2-11eb-839b-c6b719a7cf46.png)

**Comment by pangolp** [comment]
Were you able to solve this problem?

**Comment by noxcis12** [comment]
no :/

**Comment by pangolp** [comment]
> no :/

In the image you can not see the error, if not, create the item, and leave it in the store, so you can see what is the error that is generated.

**Comment by noxcis12** [comment]
i create 1 top item

**Comment by pangolp** [comment]
I have no way to see the error, take a screenshot of the form where you created the item, to know what values you put. If there is a password or information that you can't display, then hide it, but I need to see how you created it, because I don't have much information about the error.

**Comment by noxcis12** [comment]
![create_item](https://user-images.githubusercontent.com/85730526/121825225-7fc7a480-ccb1-11eb-9690-60a719ad681f.png)
![create_item2](https://user-images.githubusercontent.com/85730526/121825231-835b2b80-ccb1-11eb-881b-cae31cf1dce7.png)

**Comment by pangolp** [comment]
It seems to be a bug in the code, but I'm not sure. I would have to do some tests to check the bug and really know if it is a bug or not.

**Comment by pangolp** [comment]
![store_items](https://user-images.githubusercontent.com/2810187/121825433-bb01ad80-cc88-11eb-8288-57b8c5eb72a4.png)

![store_top](https://user-images.githubusercontent.com/2810187/121825437-bccb7100-cc88-11eb-9c75-9df061d8817e.png)

**Comment by noxcis12** [comment]
d'accord
![store](https://user-images.githubusercontent.com/85730526/121825511-26f90b80-ccb3-11eb-9e3e-9ed6840c6eef.png)

this is the correct ID

**Comment by pangolp** [comment]
Yes, in the end it is a bug in the module.
Now I will pass it to my colleagues so they can apply the changes. But you will have to update the code later, once it is added.

![top_items](https://user-images.githubusercontent.com/2810187/121826013-e89c2600-cc8b-11eb-9c35-18f4b192963a.png)

**Comment by noxcis12** [comment]
Ok thank you very much :)

**Comment by pangolp** [comment]
The change has already been applied, you should update the code and the error should disappear.
